services:
  money:
    image: nexus.jbrmmg.me.uk:8084/money:latest
    container_name: money
    restart: unless-stopped
    ports:
      - "12017:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_H2_CONSOLE_ENABLED=false
      - MONEY_REGULAR_ENABLED=true
      - MONEY_REPORT_ENABLED=true
      - MONEY_ARCHIVE_ENABLED=true
    volumes:
      - money-logs:/app/logs
      - money-working:/app/reports/working
      - /media/Shared/Documents/PDF/MoneyReports:/app/reports/share
      - /home/jason/Downloads:/app/reconcile
    networks:
      - jbr_networks

volumes:
  money-logs:
  money-working:

networks:
  jbr-network:
    external: true