services:
  money-dev:
    image: nexus.jbrmmg.me.uk:8084/money-dev:latest
    container_name: money-dev
    restart: unless-stopped
    ports:
      - "10017:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_H2_CONSOLE_ENABLED=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    volumes:
      - money-dev-logs:/app/logs
      - money-dev-working:/app/reports/working
      - /var/money/report:/app/reports/share
      - /var/money/reconcile:/app/reconcile
    networks:
      - jbr-network

volumes:
  money-dev-logs:
  money-dev-working:

networks:
  jbr-network:
    external: true
