logging:
    level:
        ROOT: INFO
        com.jbr.middletier: DEBUG
        org.hibernate.type.descriptor.sql: TRACE

spring:
    liquibase:
      default-schema:
      change-log: classpath:/db/changelog/db.changelog-master-dbg.yaml

    jpa:
      properties:
        hibernate:
          format_sql: true
      show-sql: true

server:
    port: 13017

info:
    app:
        version: Debug

money:
    reconcile-file-location: /home/jason/Working/DbgReconcilation/
