logging:
  level:
    ROOT: INFO
    com.jbr.middletier: DEBUG

spring:
  datasource:
    url: ${db.pdn.money.server}?autoReconnect=true&useSSL=false
    username: ${db.pdn.money.user}
    password: ${db.pdn.money.password}

  liquibase:
    contexts:
    enabled: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 13017

money:
  report-working: /home/jason/Working/DbgReport/
  report-share: /home/jason/Working/DbgReportShare/
  report-schedule: 0 23 * * * ?
  report-enabled: true

info:
  app:
    version: Debug
