spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${db.pdn.money.server}?autoReconnect=true&useSSL=false
    username: ${db.pdn.money.user}
    password: ${db.pdn.money.password}
    hikari:
      poolName: Hikari
      auto-commit: false

    h2:
      console:
      enabled: false

  boot:
    admin:
      client:
        url: ${spring.admin.clienturl}

server:
  port: 12017

info:
  app:
    version: Production
