spring:
    datasource:
        url: ${db.pdn.money.server}?autoReconnect=true&useSSL=false
        username: ${db.pdn.money.user}
        password: ${db.pdn.money.password}

    application:
        name: Middle Tier Money

    h2:
      console:
        enabled: false

logging:
    file:
        name: /var/log/jbr/MiddleTier-MoneyDB-PDN.log
    logback:
        rollingpolicy:
            max-file-size: 100MB
            max-history: 3

server:
    port: 12017

money:
    service-name: middletier-money
    report-share: /media/Shared/Documents/PDF/MoneyReports
    report-working: /home/jason/Working/PdnReport/
    regular-enabled: true
    report-enabled: true
    archive-enabled: true
    reconcile-file-location: /home/jason/Downloads

info:
    app:
        version: Production
