spring:
    datasource:
        url: ${db.pdn.money.server}?autoReconnect=true&useSSL=false
        username: ${db.pdn.money.user}
        password: ${db.pdn.money.password}

    boot:
        admin:
            client:
                url: ${spring.admin.clienturl}


    application:
        name: Middle Tier Money

    h2:
      console:
        enabled: false

logging.file: /var/log/jbr/MiddleTier-MoneyDB-PDN.log
logging:
    file:
        max-history: 3
        max-size: 100MB

server:
    port: 12017

money:
    service-name: middletier-money
    web-log-url: http://localhost:12001/jbr/int/log/data
    report-share: /media/Shared/Documents/PDF/MoneyReports
    report-working: /home/jason/Working/PdnReport/
    regular-enabled: true
    report-enabled: true

info:
    app:
        version: Production
