logging:
  level:
    ROOT: INFO
    com.jbr.middletier: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

spring:
  datasource:
    url: ${db.dev.money.server}?autoReconnect=true&useSSL=false
    username: ${db.dev.money.user}
    password: ${db.dev.money.password}

  liquibase:
    contexts:
    enabled: false

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 13017

money:
  service-name: middletier-money-dbg
  web-log-url: http://localhost:10001/jbr/int/log/data
  report-working: /home/jason/Working/DbgReport/
  report-share: /home/jason/Working/DbgReportShare/
  report-schedule: 0 23 * * * ?
  report-enabled: true

info:
  app:
    version: Debug
